# Generated by Django 5.2 on 2025-05-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
