# Generated by Django 5.2 on 2025-05-05 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='author/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Şəkil'),
        ),
    ]
