# Generated by Django 5.2 on 2025-05-06 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_author_options_alter_gender_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax qiymət'),
        ),
    ]
