# Generated by Django 5.2 on 2025-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price_alter_product_tax_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-poçt'),
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Şifrə'),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='İstiadəçi adı'),
        ),
    ]
