# Generated by Django 5.2 on 2025-05-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_changepasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-poçt'),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='İstiadəçi adı'),
        ),
    ]
