# Generated by Django 5.2 on 2025-05-29 17:31

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_author_email_alter_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepasswordtoken',
            name='expire_date',
            field=models.DateTimeField(default=product.models.ChangePasswordToken.default_expire),
        ),
        migrations.AlterField(
            model_name='changepasswordtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
